import os
import subprocess
from music21 import converter
import onnxruntime

# Preload DLLs to avoid CUDA errors
onnxruntime.preload_dlls(cuda=False, cudnn=False, msvc=True)

def convert_to_midi(input_path):
    output_dir = "outputs"
    os.makedirs(output_dir, exist_ok=True)

    # Disable GPU for ONNX Runtime
    env = os.environ.copy()
    env["ORT_DISABLE_GPU"] = "1"

    result = subprocess.run(
        ["oemer", input_path, "-o", output_dir],
        capture_output=True,
        text=True,
        env=env
    )

    if result.returncode != 0:
        raise RuntimeError(f"Oemer failed: {result.stderr}")

    musicxml_path = next(
        (os.path.join(output_dir, f) for f in os.listdir(output_dir) if f.endswith(".musicxml")),
        None
    )

    if not musicxml_path:
        raise FileNotFoundError("No MusicXML file generated by Oemer.")

    score = converter.parse(musicxml_path)
    midi_path = musicxml_path.replace(".musicxml", ".mid")
    score.write('midi', fp=midi_path)

    return midi_path
