import os
import subprocess
from music21 import converter

def convert_to_midi(input_path):
    # Step 1: Prepare output folder
    output_dir = "outputs"
    os.makedirs(output_dir, exist_ok=True)

    # Step 2: Set environment to disable GPU (this is the key fix)
    env = os.environ.copy()
    env["ORT_DISABLE_GPU"] = "1"

    # Step 3: Run Oemer CLI with environment override
    result = subprocess.run(
        ["oemer", input_path, "-o", output_dir],
        capture_output=True,
        text=True,
        env=env  # 👈 Important
    )

    if result.returncode != 0:
        raise RuntimeError(f"Oemer failed: {result.stderr}")

    # Step 4: Locate the generated MusicXML file
    musicxml_path = None
    for file in os.listdir(output_dir):
        if file.endswith(".musicxml"):
            musicxml_path = os.path.join(output_dir, file)
            break

    if not musicxml_path:
        raise FileNotFoundError("No MusicXML file generated by Oemer.")

    # Step 5: Convert MusicXML to MIDI
    score = converter.parse(musicxml_path)
    midi_path = musicxml_path.replace(".musicxml", ".mid")
    score.write('midi', fp=midi_path)

    return midi_path
